@startuml

start
:array = new int(10) ]

partition readData {
	while (console hava input data?)
		:read data/
		:add read number to array;
	endwhile
}

partition calculateSum {
	:sum = 0
	i=0|
	while(i < size of array)  
	:sum = sum + array[i];
	:i++]
	endwhile
}

partition printResults {
	repeat 
		:print item of array/
	repeat while (more data?)
}

stop
@enduml
