tabla = [{id: 2, tier1: 'Comunicaciones', tier2: 'Red', tier3: 'Datos', tier4: 'Falla con el servicio de Internet inalámbrica'},
{id: 3, tier1: 'Comunicaciones', tier2: 'Red', tier3: 'Voz', tier4: 'Falla con el servicio de voz (extensiones)'},
{id: 4, tier1: 'Comunicaciones', tier2: 'Red', tier3: 'Datos', tier4: 'Fallas en la sala de conferencias'},
{id: 5, tier1: 'Comunicaciones', tier2: 'Red', tier3: 'Datos', tier4: 'Restablecer contraseña red inalámbrica'},
{id: 6, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Acceso', tier4: 'Falla con el acceso al equipo de cómputo'},
{id: 7, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Voz', tier4: 'Falla de Audio'},
{id: 8, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Componente', tier4: 'Falla de batería'},
{id: 9, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Componente', tier4: 'Falla de Monitor'},
{id: 10, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Componente', tier4: 'Falla de Mousepad'},
{id: 11, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Componente', tier4: 'Falla de Puertos'},
{id: 12, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Componente', tier4: 'Falla de Teclado'},
{id: 13, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Componente', tier4: 'Falla del cargador'},
{id: 14, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Análisis', tier4: 'Revisión de Equipo'},
{id: 15, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Análisis', tier4: 'Sobrecalentamiento de equipo'},
{id: 16, tier1: 'Hardware', tier2: 'Periféricos', tier3: 'Componente', tier4: 'Configuración de Impresora'},
{id: 17, tier1: 'Hardware', tier2: 'Periféricos', tier3: 'Componente', tier4: 'Falla de Impresora'},
{id: 18, tier1: 'Hardware', tier2: 'Periféricos', tier3: 'Componente', tier4: 'Falla de Escáner'},
{id: 19, tier1: 'Hardware', tier2: 'Periféricos', tier3: 'Compra', tier4: 'Impresora sin Tóner'},
{id: 20, tier1: 'Hardware', tier2: 'Telefonía', tier3: 'Voz', tier4: 'Falla con equipo telefónico'},
{id: 22, tier1: 'Mensajería', tier2: 'Correo', tier3: 'Análisis', tier4: 'Caída de Correo'},
{id: 23, tier1: 'Mensajería', tier2: 'Correo', tier3: 'Acceso', tier4: 'Falla con el acceso al correo'},
{id: 24, tier1: 'Software', tier2: 'Alojamiento', tier3: 'Nube', tier4: 'Falla de alojamiento en la nube'},
{id: 25, tier1: 'Software', tier2: 'Alojamiento', tier3: 'Físico', tier4: 'Falla de alojamiento físico'},
{id: 26, tier1: 'Software', tier2: 'Alojamiento', tier3: 'Virtual', tier4: 'Falla de alojamiento virtual'},
{id: 27, tier1: 'Software', tier2: 'Antivirus', tier3: 'Análisis', tier4: 'Alerta de Virus'},
{id: 28, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Explorador', tier4: 'Falla con el Explorador'},
{id: 29, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Explorador', tier4: 'Falla con el Explorador en FMS'},
{id: 30, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Explorador', tier4: 'Falla con el Explorador en IAS'},
{id: 31, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Treffpunk', tier4: 'Falla de Software Treffpunk'},
{id: 32, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Dipros', tier4: 'Falla de Software Reloj Checador'},
{id: 33, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Office', tier4: 'Falla de Software Office 2010 (Toda la paquetería)'},
{id: 34, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Office', tier4: 'Falla de Software Office 2013 (Toda la paquetería)'},
{id: 35, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Cargo Sphere', tier4: 'Falla de Software Cargo Sphere'},
{id: 36, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Skype', tier4: 'Falla de Software Skype'},
{id: 37, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Bit defender', tier4: 'Falla de Software Bit defender'},
{id: 38, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Veramiko', tier4: 'Falla de Software Veramiko'},
{id: 39, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Adobe Acrobat', tier4: 'Falla de Software Adobe Acrobat'},
{id: 40, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Acronis', tier4: 'Falla de Software Acronis'},
{id: 42, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Compaq', tier4: 'Falla de Software Compaq'},
{id: 43, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Firefox', tier4: 'Falla de Software Firefox'},
{id: 44, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Cargo Wise', tier4: 'Falla de Software Cargo Wise'},
{id: 45, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Logmein', tier4: 'Falla de Software Logmein'},
{id: 46, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Nominpaq', tier4: 'Falla de Software Nominpaq'},
{id: 47, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Java', tier4: 'Falla de Software Java'},
{id: 50, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'SharePoint', tier4: 'Falla con acceso a SharePoint'},
{id: 51, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Móviles', tier4: 'Falla con aplicaciones de dispositivos Móviles'},
{id: 53, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Falla en el sistema de FMS'},
{id: 54, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Análisis', tier4: 'Falla con el sistema de circuito cerrado'},
{id: 55, tier1: 'Software', tier2: 'Mensajería', tier3: 'Live meeting', tier4: 'Falla de Software Live meeting'},
{id: 56, tier1: 'Software', tier2: 'Mensajería', tier3: 'Lync', tier4: 'Falla de Software Lync'},
{id: 57, tier1: 'Apertura', tier2: 'Aplicaciones', tier3: 'Análisis', tier4: 'Solicitar análisis de factibilidad'},
{id: 58, tier1: 'Apertura', tier2: 'Negocio', tier3: 'Workplace', tier4: 'Solicitar apertura de workplace'},
{id: 59, tier1: 'Comunicaciones', tier2: 'Red', tier3: 'Datos', tier4: 'Interconexión en sala de conferencias'},
{id: 60, tier1: 'Comunicaciones', tier2: 'Red', tier3: 'Datos', tier4: 'Solicitud de servicios de internet'},
{id: 61, tier1: 'Comunicaciones', tier2: 'Red', tier3: 'Voz', tier4: 'Solicitud de servicios de voz (extensiones)'},
{id: 62, tier1: 'Comunicaciones', tier2: 'Red', tier3: 'Acceso', tier4: 'Solicitud de usuarios y contraseñas'},
{id: 63, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Compra', tier4: 'Requerimiento de Equipo de Cómputo'},
{id: 65, tier1: 'Hardware', tier2: 'Periféricos', tier3: 'Compra', tier4: 'Solicitud de equipo de Impresión'},
{id: 66, tier1: 'Hardware', tier2: 'Periféricos', tier3: 'Compra', tier4: 'Solicitud de scanner'},
{id: 67, tier1: 'Hardware', tier2: 'Telefonía', tier3: 'Compra', tier4: 'Solicitar Compras - Reabastecimiento de Stock'},
{id: 68, tier1: 'Hardware', tier2: 'Telefonía', tier3: 'Compra', tier4: 'Requerimiento de Equipo telefónico'},
{id: 69, tier1: 'Mensajería', tier2: 'Correo', tier3: 'Actualización', tier4: 'Modificación y configuración al servicio de correo'},
{id: 70, tier1: 'Mensajería', tier2: 'Correo', tier3: 'Actualización', tier4: 'Reemplazo de cuenta de correo'},
{id: 71, tier1: 'Software', tier2: 'Alojamiento', tier3: 'Nube', tier4: 'Solicitar alojamiento en la nube'},
{id: 72, tier1: 'Software', tier2: 'Alojamiento', tier3: 'Físico', tier4: 'Solicitar alojamiento físico'},
{id: 73, tier1: 'Software', tier2: 'Alojamiento', tier3: 'Virtual', tier4: 'Solicitar alojamiento virtual'},
{id: 74, tier1: 'Software', tier2: 'Antivirus', tier3: 'Actualización', tier4: 'Actualización de Antivirus'},
{id: 75, tier1: 'Software', tier2: 'Antivirus', tier3: 'Instalación', tier4: 'Instalación de antivirus'},
{id: 76, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Instalación', tier4: 'Instalación de Software'},
{id: 77, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Actualización', tier4: 'Solicitar aplicaciones para dispositivos Móviles'},
{id: 78, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Análisis Diseño', tier4: 'Solicitar un nuevo desarrollo'},
{id: 79, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Actualización', tier4: 'Actualización de Sistema Operativo'},
{id: 80, tier1: 'Software', tier2: 'Respaldos', tier3: 'PC', tier4: 'Solicitar respaldos de sistema manual'},
{id: 81, tier1: 'Software', tier2: 'Respaldos', tier3: 'Servidor', tier4: 'Solicitar respaldos de servidores'},
{id: 82, tier1: 'Software', tier2: 'Respaldos', tier3: 'Servidor', tier4: 'Solicitar respaldos de correo electrónico'},
{id: 83, tier1: 'Hardware', tier2: 'Periféricos', tier3: 'Componente', tier4: 'Configuración de Escáner'},
{id: 1006, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Sharepoint-Dashboard', tier4: 'Falla en acceso a la plataforma'},
{id: 1007, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Sharepoint-Wiki', tier4: 'Falla en acceso a la plataforma'},
{id: 1008, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Sharepoint-Dashboard', tier4: 'Falla al subir documentos'},
{id: 1009, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'SharePoint-Comprobantes', tier4: 'Falla al subir documentos'},
{id: 1010, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Sharepoint-Wiki', tier4: 'Falla al subir documentos'},
{id: 1011, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Sharepoint-Dashboard', tier4: 'Falla en la asignación de permiso'},
{id: 1012, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Sharepoint-Dashboard', tier4: 'Falta de espacio en el área'},
{id: 1013, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Facturación', tier4: 'Solicitud de Adendda'},
{id: 1014, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Facturación', tier4: 'Modificación de plantila factura'},
{id: 1015, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Facturación', tier4: 'Modificación de txt'},
{id: 1016, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Facturación', tier4: 'Cancelacion de proceso en envio de documento'},
{id: 1017, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Sharepoint', tier4: 'Alta de permisos en sharepoint'},
{id: 1018, tier1: 'Otros', tier2: '', tier3: '', tier4: ''},
{id: 1019, tier1: 'Otros', tier2: '', tier3: '', tier4: ''},
{id: 1020, tier1: 'Hardware', tier2: 'Periféricos', tier3: 'Componente', tier4: 'Configuración de Impresora'},
{id: 1021, tier1: 'Mensajería', tier2: 'Correo', tier3: 'Configuración', tier4: 'Alta de correo'},
{id: 1100, tier1: 'Mensajería', tier2: 'Correo', tier3: 'Configuración', tier4: 'Configuración de Outlook APP'},
{id: 1101, tier1: 'Mensajería', tier2: 'Correo', tier3: 'Configuración', tier4: 'Generar lista de distribución'},
{id: 1102, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Falla en Booking'},
{id: 1104, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Falla en Facturas'},
{id: 1105, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Falla en Provisiones'},
{id: 1106, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Falla en CPA'},
{id: 1107, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Falla en envío de Alertas'},
{id: 1108, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Falla en Master'},
{id: 1109, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Otros'},
{id: 1110, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Cambios en ETD y ETA'},
{id: 1111, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Alta de Location'},
{id: 1112, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Alta de Usuario'},
{id: 1113, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Modificación de Usuario'},
{id: 1114, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Solicitud de Reporte'},
{id: 1115, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Alta de Cargos'},
{id: 1116, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Alta de Puerto'},
{id: 1117, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Alta de Aeropuerto'},
{id: 1118, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Permiso para Facturar'},
{id: 1119, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Permiso para Provisionar'},
{id: 1123, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'IAS', tier4: 'Falla con información de Cheques'},
{id: 1124, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'IAS', tier4: 'Falla de aplicación de Depositos'},
{id: 1125, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'IAS', tier4: 'Otros'},
{id: 1127, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'IAS', tier4: 'Alta de Articulos (Items)'},
{id: 1128, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'IAS', tier4: 'Permiso para eliminación de cheques'},
{id: 1129, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'IAS', tier4: 'Otros'},
{id: 1130, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Salesforce', tier4: 'Ingreso a Salesforce'},
{id: 1131, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Salesforce', tier4: 'Reestablecer contraseña'},
{id: 1132, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Salesforce', tier4: 'Confirmación de códigos de verificación'},
{id: 1133, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Salesforce', tier4: 'Alta de nuevos usuario'},
{id: 1134, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Salesforce', tier4: 'Calificación de potencial de cuenta'},
{id: 1135, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Salesforce', tier4: 'Registro de citas'},
{id: 1136, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Salesforce', tier4: 'Agregar Location'},
{id: 1137, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Salesforce', tier4: 'Cotizaciones'},
{id: 1138, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Salesforce', tier4: 'Citas'},
{id: 1139, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'SAP', tier4: 'Falla en sincronizacion'},
{id: 1126, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'IAS', tier4: 'Alta de Cuentas Bancarias'},
{id: 1, tier1: 'Comunicaciones', tier2: 'Red', tier3: 'Datos', tier4: 'Falla con el servicio de Internet de cable'},
{id: 21, tier1: 'Mensajería', tier2: 'Correo', tier3: 'Análisis', tier4: 'Falla con el servicio de Correo'},
{id: 41, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'Navegate', tier4: 'Falla de Software Navegate'},
{id: 64, tier1: 'Hardware', tier2: 'Equipo de cómputo', tier3: 'Compra', tier4: 'Solicitar Compras - Reabastecimiento de Stock'},
{id: 1005, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'SharePoint-Comprobantes', tier4: 'Falla en acceso a la plataforma'},
{id: 1103, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'FMS', tier4: 'Falla en Billing'},
{id: 1126, tier1: 'Software', tier2: 'Aplicaciones', tier3: 'IAS', tier4: 'Alta de Cuentas Bancarias'}]

mapa = {}

tabla.each do | renglon |
	unless mapa[renglon[:tier1]]
		mapa[renglon[:tier1]] = {}
	end
	unless mapa[renglon[:tier1]][renglon[:tier2]]
		mapa[renglon[:tier1]][renglon[:tier2]] = {}
	end
	unless mapa[renglon[:tier1]][renglon[:tier2]][renglon[:tier3]]
		mapa[renglon[:tier1]][renglon[:tier2]][renglon[:tier3]] = {}
	end
	mapa[renglon[:tier1]][renglon[:tier2]][renglon[:tier3]][renglon[:id].to_s] = renglon[:tier4] 
end

File.open('mapa.json', 'w') do |f|
	f.write mapa.to_s
end
p mapa