@startuml

participant ArraySumProgram 

activate ArraySumProgram
ArraySumProgram -> InputReader : call

activate InputReader
InputReader -> Console : read data from
	loop n times
	InputReader <-- Console : data read
	end
ArraySumProgram <-- InputReader : data read
deactivate InputReader
ArraySumProgram -> ArraySummarizer : executes sum
ArraySummarizer -> ArrayOfNumbers : getData
ArraySummarizer <-- ArrayOfNumbers 
ArraySumProgram <-- ArraySummarizer
	ArraySumProgram -> Console : print result
deactivate ArraySumProgram
@enduml